### ISSUE TITLE
Open Source Repo

### ISSUE THREAD

**Issue by YurkoWasHere** [starlinglab/archive-explorer#13]
- [x]  Release  V1 (0.0.1?)
- [x] Add Copyright (Match integrity repos?)
- [x] Release Open Source
- [x] Add CI Publish Git Hub Pages (Stretch)
-  ~Add README~ -> #19

**Comment by tripledoublev** [comment]
Now [published](https://starlinglab.github.io/archive-explorer/) to github pages
